library("tidyverse")

all_error <- readr::read_tsv(
    "all_last_mapq.tsv",
    col_types = c(
        FILENAME = col_character(),
        INSERTION = col_double(),
        DELETION = col_double(),
        MATCH = col_double(),
        SUBSTITUTION = col_double()
    )
) %>%
    dplyr::mutate(
        FILENAME=stringr::str_replace(FILENAME, "ce11_as_2_accu_", "")
    ) %>%
    dplyr::mutate(
        FILENAME=stringr::str_replace(FILENAME, ".maf", "")
    ) %>%
    tidyr::gather(
        key = "EventType",
        value = "EventCount",
        -FILENAME
    ) %>%
    dplyr::mutate(
        EventType=factor(EventType, levels=c("DELETION", "INSERTION", "SUBSTITUTION", "MATCH"))
    )

g <- ggplot(all_error) +
    geom_bar(
        aes(
            y = FILENAME,
            x = EventCount,
            fill = EventType
        ),
        position = "fill",
        stat = "identity"
    ) +
    theme_bw() +
    scale_x_continuous("Event Frequency") +
    scale_y_discrete("Data Spec") +
    scale_color_manual("Event Type") +
    ggtitle("Error Rate Generated by MAF from LLRGs")
ggsave("maf_error_rate.pdf", g, width = 8, height = 5)

