# Test Analysis over Nanopore Data


```{r Load Package}
load_package <- function(name) {
    message(sprintf("Loading %s", name))
    suppressWarnings(suppressMessages(library(name, quietly = TRUE, warn.conflicts = FALSE, character.only = TRUE)))
}

load_package("tidyverse")
load_package("ggpubr")
load_package("gamlss")
load_package("fitdistrplus")
load_package("parallel")
load_package("knitr")
load_package("rmutil")

knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width = 16)
knitr::opts_chunk$set(cache = TRUE)
sessionInfo()
version

cl <- parallel::makeCluster(parallel::detectCores() - 1)
clusterExport(cl, varlist = ls())

all_data <- read_tsv("../all_data.tsv")

all_data_nano <- all_data %>%
    dplyr::select(TRANSCRIPT_ID, GENE_ID, SEQNAME, START, END, STRAND, LEN, GC, NANOPORE_AVG_DEPTH) %>%
    dplyr::rename(count=NANOPORE_AVG_DEPTH) %>%
    dplyr::filter(count>0)
all_data_pacb <- all_data %>%
    dplyr::select(TRANSCRIPT_ID, GENE_ID, SEQNAME, START, END, STRAND, LEN, GC, PACB_AVG_DEPTH) %>%
    dplyr::rename(count=PACB_AVG_DEPTH) %>%
    dplyr::filter(count>0)
all_data_illm1 <- all_data %>%
    dplyr::select(TRANSCRIPT_ID, GENE_ID, SEQNAME, START, END, STRAND, LEN, GC, ILLM1_AVG_DEPTH) %>%
    dplyr::rename(count=ILLM1_AVG_DEPTH) %>%
    dplyr::filter(count>0)
all_data_illm2 <- all_data %>%
    dplyr::select(TRANSCRIPT_ID, GENE_ID, SEQNAME, START, END, STRAND, LEN, GC, ILLM2_AVG_DEPTH) %>%
    dplyr::rename(count=ILLM2_AVG_DEPTH) %>%
    dplyr::filter(count>0)
all_data_illm3 <- all_data %>%
    dplyr::select(TRANSCRIPT_ID, GENE_ID, SEQNAME, START, END, STRAND, LEN, GC, ILLM3_AVG_DEPTH) %>%
    dplyr::rename(count=ILLM3_AVG_DEPTH) %>%
    dplyr::filter(count>0)
```

```{r test ziff's law}
all_data_nano <- all_data_nano %>%
    dplyr::mutate(
        rank=dplyr::dense_rank(dplyr::desc(count)),
        zipfs_freq = max(count) / rank,
        rank_l2n=log2(rank),
        zipfs_freq_l2n=log2(zipfs_freq),
        count_l2n=log2(count),
    )
flnorm_nano <- fitdistrplus::fitdist(all_data_nano$count, "lnorm")
flnorm_pacb <- fitdistrplus::fitdist(all_data_pacb$count, "lnorm")
flnorm_illm1 <- fitdistrplus::fitdist(all_data_illm1$count, "lnorm")
flnorm_illm2 <- fitdistrplus::fitdist(all_data_illm2$count, "lnorm")
flnorm_illm3 <- fitdistrplus::fitdist(all_data_illm3$count, "lnorm")

hist(rlnorm(c(1:10e5), flnorm_nano$estimate))

```
