---
title: "Satistical Analysis on Merged C. Elegans Dataset"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggpubr)
library(gamlss)
library(fitdistrplus)
library(parallel)
```


```{r}
all_data <- read_tsv("../all_data.tsv")

NANOPORE_AVG_DEPTH <- all_data$NANOPORE_AVG_DEPTH %>% .[! . == 0]
PACB_AVG_DEPTH <- all_data$PACB_AVG_DEPTH %>% .[! . == 0]
ILLM1_AVG_DEPTH <- all_data$ILLM1_AVG_DEPTH %>% .[! . == 0]

fit_gamma_ont <- fitdistrplus::fitdist(NANOPORE_AVG_DEPTH, "gamma")
fit_nb_ont <- fitdistrplus::fitdist(as.integer(NANOPORE_AVG_DEPTH), "nbinom")
fit_gamma_pacb <- fitdistrplus::fitdist(PACB_AVG_DEPTH, "gamma")
fit_nb_pacb <- fitdistrplus::fitdist(as.integer(PACB_AVG_DEPTH), "nbinom")
# fit_gamma_illm <- fitdistrplus::fitdist(ILLM1_AVG_DEPTH, "gamma")
fit_nb_illm <- fitdistrplus::fitdist(as.integer(ILLM1_AVG_DEPTH), "nbinom")

fit_gamma_ont$aic > fit_nb_ont$aic
fit_gamma_pacb$aic > fit_nb_pacb$aic

fit_gamma_ont$bic > fit_nb_ont$bic
fit_gamma_pacb$bic > fit_nb_pacb$bic



```


```{r}
cl <- parallel::makeCluster(parallel::detectCores()-1)

clusterExport(cl, varlist = ls())
```


```{r}
psr <- parSapply(cl, 1:1e3, function(x){
    c(
        fitdistrplus::fitdist(as.integer(
            sample(NANOPORE_AVG_DEPTH, as.integer(length(NANOPORE_AVG_DEPTH)/10))
        ), "nbinom")$estimate,
        fitdistrplus::fitdist(as.integer(
            sample(PACB_AVG_DEPTH, as.integer(length(PACB_AVG_DEPTH)/10))
        ), "nbinom")$estimate,
        fitdistrplus::fitdist(as.integer(
            sample(ILLM1_AVG_DEPTH, as.integer(length(ILLM1_AVG_DEPTH)/10))
        ), "nbinom")$estimate
    )
})
```
